import { APP_PATH, GenericObject } from 'models'

export enum DocuwebPaths {
    FILM_0,
    FILM_1,
    FILM_2,
    FILM_3,
    FILM_4,
    FILM_5,
    FILM_6,
    FILM_7,
    FILM_8,
    FILM_9,
    FILM_10,
    FILM_11,
    FILM_12,
    FILM_13,
    FILM_14,
    FILM_15,
    FILM_16,
    FILM_17,
    FILM_18,
    FILM_19,
    FILM_20,
    FILM_21,
    FILM_22,
    FILM_23,
    FILM_24,
    FILM_25,
    FILM_26,
    FILM_27,
    FILM_28,
    FILM_29,
    FILM_30,
}
export const registry: GenericObject = {
    [DocuwebPaths.FILM_0]: { base: APP_PATH.VIDEO, path: 'inicio.mp4' },
    [DocuwebPaths.FILM_1]: { base: APP_PATH.VIDEO, path: 'serpientes_diversas.mp4' },
    [DocuwebPaths.FILM_2]: { base: APP_PATH.VIDEO, path: 'manejo_de_serpientes.mp4' },
    [DocuwebPaths.FILM_3]: { base: APP_PATH.VIDEO, path: 'cascabeles_libres.mp4' },
    [DocuwebPaths.FILM_4]: { base: APP_PATH.VIDEO, path: 'libertad_y_generaciones_futuras.mp4' },
    [DocuwebPaths.FILM_5]: {
        base: APP_PATH.VIDEO,
        path: 'territorios_acuaticos_cruzados_desde_dron.mp4',
    },
    [DocuwebPaths.FILM_6]: { base: APP_PATH.VIDEO, path: 'montanas_de_metztitlan.mp4' },
    [DocuwebPaths.FILM_7]: {
        base: APP_PATH.VIDEO,
        path: 'cuidado_de_serpientes_desde_la_mirada_de_herpetologos_.mp4',
    },
    [DocuwebPaths.FILM_8]: { base: APP_PATH.VIDEO, path: 'miradas_de_serpientes.mp4' },
    [DocuwebPaths.FILM_9]: { base: APP_PATH.VIDEO, path: 'defensa_de_serpientes.mp4' },
    [DocuwebPaths.FILM_10]: {
        base: APP_PATH.VIDEO,
        path: 'conservacion_de_serpientes_sin_mordidas.mp4',
    },
    [DocuwebPaths.FILM_11]: { base: APP_PATH.VIDEO, path: 'remedios_caseros_y_mordidas.mp4' },
    [DocuwebPaths.FILM_12]: { base: APP_PATH.VIDEO, path: 'historias_de_encuentros.mp4' },
    [DocuwebPaths.FILM_13]: { base: APP_PATH.VIDEO, path: 'testimonio_de_una_mordida.mp4' },
    [DocuwebPaths.FILM_14]: {
        base: APP_PATH.VIDEO,
        path: 'el_pasado_de_las_y_los_brigadistas.mp4',
    },
    [DocuwebPaths.FILM_15]: {
        base: APP_PATH.VIDEO,
        path: 'brigadistas_que_cuidan_a_pesar_del_miedo.mp4',
    },
    [DocuwebPaths.FILM_16]: {
        base: APP_PATH.VIDEO,
        path: 'como_han_enfrentado_el_miedo_a_las_serpientes_las_y_los_brigadistas.mp4',
    },
    [DocuwebPaths.FILM_17]: {
        base: APP_PATH.VIDEO,
        path: 'de_donde_viene_el_miedo_a_las_serpientes.mp4',
    },
    [DocuwebPaths.FILM_18]: { base: APP_PATH.VIDEO, path: 'mitos_enredados_entre_serpientes.mp4' },
    [DocuwebPaths.FILM_19]: { base: APP_PATH.VIDEO, path: 'la_transformacion_del_miedo.mp4' },
    [DocuwebPaths.FILM_20]: {
        base: APP_PATH.VIDEO,
        path: 'el_trabajo_de_las_y_los_brigadistas.mp4',
    },
    [DocuwebPaths.FILM_21]: { base: APP_PATH.VIDEO, path: 'experiencias_para_ser_brigadistas.mp4' },
    [DocuwebPaths.FILM_22]: {
        base: APP_PATH.VIDEO,
        path: 'la_busqueda_de_otras_relaciones_con_las_serpientes.mp4',
    },
    [DocuwebPaths.FILM_23]: {
        base: APP_PATH.VIDEO,
        path: 'mordida_de_serpiente_a_un_herpetologo_.mp4',
    },
    [DocuwebPaths.FILM_24]: { base: APP_PATH.VIDEO, path: 'la_intencion_nunca_es_atacar.mp4' },
    [DocuwebPaths.FILM_25]: { base: APP_PATH.VIDEO, path: 'metztitan_espacio_de_brigadistas.mp4' },
    [DocuwebPaths.FILM_26]: { base: APP_PATH.VIDEO, path: 'desde_las_serpientes.mp4' },
    [DocuwebPaths.FILM_27]: {
        base: APP_PATH.VIDEO,
        path: 'la_maravilla_del_veneno_de_serpiente.mp4',
    },
    [DocuwebPaths.FILM_28]: { base: APP_PATH.VIDEO, path: 'el_carino_a_las_serpientes_.mp4' },
    [DocuwebPaths.FILM_29]: { base: APP_PATH.VIDEO, path: 'conozcamos_a_las_serpientes.mp4' },
    [DocuwebPaths.FILM_30]: {
        base: APP_PATH.VIDEO,
        path: 'llevar_las_serpientes_a_las_comunidades.mp4',
    },
}
