// Autogenerated file run "yarn mk-locales"

export const validTranslationKeys = {
    es: {
        'common:menu.home': 'Dashboard',
        'common:menu.schemas': 'Schemas',
        'common:menu.content': 'Contenidos',
        'common:menu.endpoints': 'Endpoints',
        'common:menu.nodes': 'Nodos',
        'common:menu.uploads': 'Uploads',
        'common:menu.logout': 'Cerrar sesión',
        'endpoints:save': 'Guardar',
        'video:titles.videoName': 'Video: {{name}}',
        'video:titles.length': 'duración: {{length}}',
        'video:decisions.waitUntilFinnish': 'segundos para continuar',
        'video:player.play': 'Play',
        'video:player.pause': 'Pausa',
        'video:player.stop': 'Detener',
        'video:player.mute': 'Silenciar',
        'video:player.fullscreen': 'Pantalla completa',
        'video:player.exitFullscreen': 'Salir de pantalla completa',
        'video:player.settings': 'Configuración',
        'video:player.quality': 'Calidad',
        'video:player.subtitles': 'Subtitulos',
        'video:player.back': 'Retroceder',
        'video:player.forward': 'Avanzar',
        'video:player.replay': 'Repetir',
        'video:player.volume': 'Volumen',
        'video:player.duration': 'Duración',
        'video:player.error': 'Error',
        'video:player.loading': 'Cargando',
        'video:player.skip': 'Saltar',
    },
}

export type iKeyTranslations =
    | 'common:menu.home'
    | 'common:menu.schemas'
    | 'common:menu.content'
    | 'common:menu.endpoints'
    | 'common:menu.nodes'
    | 'common:menu.uploads'
    | 'common:menu.logout'
    | 'endpoints:save'
    | 'video:titles.videoName'
    | 'video:titles.length'
    | 'video:decisions.waitUntilFinnish'
    | 'video:player.play'
    | 'video:player.pause'
    | 'video:player.stop'
    | 'video:player.mute'
    | 'video:player.fullscreen'
    | 'video:player.exitFullscreen'
    | 'video:player.settings'
    | 'video:player.quality'
    | 'video:player.subtitles'
    | 'video:player.back'
    | 'video:player.forward'
    | 'video:player.replay'
    | 'video:player.volume'
    | 'video:player.duration'
    | 'video:player.error'
    | 'video:player.loading'
    | 'video:player.skip'

export type LangKeys = keyof typeof validTranslationKeys
