// Autogenerated file run "yarn mk-locales"

export const validTranslationKeys = {
    es: {
        'common:menu.landing': 'inicio',
        'common:menu.video': 'video',
        'common:menu.interactive': 'interactive',
        'common:menu.informative': 'informative',
        'common:menu.home': 'inicio',
        'common:menu.map': 'map',
        'landing:sponsorTitleA':
            '“Este sitio es apoyado por el Sistema de Apoyos a la Creación y Proyectos Culturales”',
        'landing:sponsorTitleB': 'Sistema de Apoyos a la Creación y Proyectos Culturales”',
        'landing:welcomeMessage':
            'Las serpientes han sido temidas, odiadas, amenazadas e incluso sacrificadas, pero ¿Podríamos tratarlas de otra manera? existen tres brigadas comunitarias en Hidalgo dispuestas a cuidarlas, conservarlas y reubicarlas; han aprendido a identificar serpientes, manejarlas e incluso atender mordidas de la mano con Nallely Morales y Leonardo Badillo, apasionados herpetólogos. Las comunidades han pasado del miedo al respeto, de matarlas a protegerlas y de contar mitos a hacer educación ambiental. Aquí podrás ser parte de su historia, conocer su pasado y aquello que les convirtió en amantes de las serpientes.',
        'landing:docuwebTitle': 'Brigadistas con piel de serpientes',
        'landing:credits': 'Créditos',
        'landing:creditsText':
            'Este sitio web fue realizado con apoyo del Sistema de Apoyos a la Creación y Proyectos Culturales de la Secretaría de Cultura de la Ciudad de México.',
        'landing:creditsLink': 'https://www.cultura.cdmx.gob.mx/',
        'landing:continue': 'Comenzar',
        'video:titles.videoName': 'Video: {{name}}',
        'video:titles.length': 'duración: {{length}}',
        'video:decisions.waitUntilFinnish': 'segundos para continuar',
        'video:player.play': 'Play',
        'video:player.pause': 'Pausa',
        'video:player.stop': 'Detener',
        'video:player.mute': 'Silenciar',
        'video:player.fullscreen': 'Pantalla completa',
        'video:player.exitFullscreen': 'Salir de pantalla completa',
        'video:player.settings': 'Configuración',
        'video:player.quality': 'Calidad',
        'video:player.subtitles': 'Subtitulos',
        'video:player.back': 'Retroceder',
        'video:player.forward': 'Avanzar',
        'video:player.replay': 'Repetir',
        'video:player.volume': 'Volumen',
        'video:player.duration': 'Duración',
        'video:player.error': 'Error',
        'video:player.loading': 'Cargando',
        'video:player.skip': 'Saltar',
    },
}

export type iKeyTranslations =
    | 'common:menu.landing'
    | 'common:menu.video'
    | 'common:menu.interactive'
    | 'common:menu.informative'
    | 'common:menu.home'
    | 'common:menu.map'
    | 'landing:sponsorTitleA'
    | 'landing:sponsorTitleB'
    | 'landing:welcomeMessage'
    | 'landing:docuwebTitle'
    | 'landing:credits'
    | 'landing:creditsText'
    | 'landing:creditsLink'
    | 'landing:continue'
    | 'video:titles.videoName'
    | 'video:titles.length'
    | 'video:decisions.waitUntilFinnish'
    | 'video:player.play'
    | 'video:player.pause'
    | 'video:player.stop'
    | 'video:player.mute'
    | 'video:player.fullscreen'
    | 'video:player.exitFullscreen'
    | 'video:player.settings'
    | 'video:player.quality'
    | 'video:player.subtitles'
    | 'video:player.back'
    | 'video:player.forward'
    | 'video:player.replay'
    | 'video:player.volume'
    | 'video:player.duration'
    | 'video:player.error'
    | 'video:player.loading'
    | 'video:player.skip'

export type LangKeys = keyof typeof validTranslationKeys
